"""results/consolidated/algorithm_code_audit.md — which implementation is which thesis algorithm.

Written before the production sweep, per the handoff's preflight requirement. It records, for every
manifest algorithm: the module-qualified function actually called, its signature, the exploration
probe(s) it takes, what it feeds to the statistical safeguard, and how N_guess / N_star /
B_exploration are defined in code. It then MEASURES the one known thesis/code mismatch instead of
asserting it away.
"""
import inspect
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
from qmetrology import manifest as M
from qmetrology.experiments import N_JOBS
from qmetrology.pipeline import _task, _chunks, seeds_for
from concurrent.futures import ProcessPoolExecutor
from qmetrology.experiments import _CTX
from qmetrology.uncertainty import wilson

PILOT_NOTE = {
    "brute": ("none -- N is fixed at N_min = floor(pi/(2 phi_max))",
              "N_guess is NULL (no exploration), B_exploration = 0, N_star = N_min"),
    "linear": ("the scan history; the depth decision is the stopping rule, not a pilot estimate",
               "N_guess = N_last - lookback_window*inc if the detector fired else N_last "
               "(before the safeguard); N_star = max(1, N_guess - s)"),
    "binary_deep": ("(phi_acc, N_acc) -- the DEEPEST probe the bisection did not flag as an "
                    "overshoot; sigma = 1/(2 N_acc sqrt(m'))",
                    "N_guess = N_acc = L; N_star = risk_optimal_depth(...), the exact argmax "
                    "over the prior support N_min = floor(pi/(2 phi_max)) .. N_max = "
                    "floor(pi/(2 phi_min))"),
    "reverse_eng_risk": ("(phi_hat_0, N_min) -- the single opening pilot; sigma = 1/(2 N_min "
                         "sqrt(m'))",
                         "N_guess = floor(pi/(2 phi_hat_0)); N_star = risk_optimal_depth(...), "
                         "the exact argmax over N_min = floor(pi/(2 phi_max)) .. N_max = "
                         "floor(pi/(2 phi_min)) -- the same range binary_deep uses"),
}


def _rate(algo, scen, budget, cfg, R, seed):
    seeds = seeds_for(seed, R)
    ch = _chunks(seeds, N_JOBS)
    tasks = [(algo, scen, budget, cfg, k, False, False) for k in ch]
    with ProcessPoolExecutor(max_workers=N_JOBS, mp_context=_CTX) as ex:
        out = list(ex.map(_task, tasks, chunksize=1))
    k = sum(o[0] for o in out)
    n = sum(o[1] for o in out)
    return k / n, k, n


def pilot_comparison(R=20_000):
    """Same seeds, same exploration, two pilots: what does resolving the mismatch actually change?

    `binary_risk` (shipped) feeds the OPENING probe to Eq. (3.8); `binary_deep` (reported) feeds the
    deepest accepted probe. Both share `_binary_search_explore`, so at one configuration the two
    differ in exactly that one input.
    """
    pts = [("narrow_e3", 10_000, 100, 0.5), ("narrow_e4", 3_000_000, 300, 0.5),
           ("small_e4", 1_000_000, 300, 0.8), ("broad_pi2_e3", 174_608, 400, 0.5)]
    rows = []
    by_id = {s["id"]: s for s in M.SCENARIOS}
    for sid, B, m, conf in pts:
        scen = by_id[sid]
        cfg = {"m_exploration": m, "conf": conf}
        a, ka, na = _rate("binary_deep", scen, B, cfg, R, M.SEED_TEST)
        # The hidden audit arm is importable in spawned Windows workers, but is not a reported
        # algorithm (it is absent from ORDER and TABLE_ORDER).
        b, kb, nb = _rate("_binary_risk_audit", scen, B, cfg, R, M.SEED_TEST)
        lo_a, hi_a = wilson(a, na)
        rows.append(dict(scenario=scen["label"], budget=B, m=m, conf=conf, R=R,
                         deep=100 * a, opening=100 * b, delta_pp=100 * (a - b),
                         deep_ci=f"[{100*lo_a:.2f}, {100*hi_a:.2f}]"))
    return rows


def build(run_comparison=True, R=20_000):
    L = []
    L.append("# Algorithm code audit\n")
    L.append("Generated by `analysis/consolidated/audit.py`. It maps every algorithm the "
             "consolidated pipeline reports onto the function that is actually executed, and records "
             "how the diagnostic quantities are defined in that code.\n")
    L.append("## Reported algorithms\n")
    L.append("| manifest key | implementation | signature | pilot fed to the safeguard | "
             "N_guess / N_star |")
    L.append("|---|---|---|---|---|")
    for k in M.ORDER:
        spec = M.ALGORITHMS[k]
        sig = str(inspect.signature(spec["fn"])).replace("|", r"\|")
        pilot, guess = PILOT_NOTE[k]
        L.append(f"| `{k}` | `{spec['variant']}` | `{sig}` | {pilot} | {guess} |")
    L.append("")
    L.append("Every one of these functions accepts an optional `trace=` collector "
             "(`qmetrology.trace.AlgorithmTrace`). The collector only records; it draws no random "
             "numbers, so a same-seed run with and without it returns identical `phi_hat` and budget "
             "use (`tests/test_consolidated.py::test_trace_neutrality`).\n")

    L.append("## The binary-search pilot mismatch\n")
    L.append("The handoff flags a material mismatch: the thesis pseudocode stores the deepest probe "
             "not classified as an overshoot (`phi_hat_acc`, `N_acc`) and supplies that pilot to the "
             "statistical safeguard, whereas "
             "`qmetrology.algorithms.find_phi_fixed_budget_binary_search_risk` supplies the opening "
             "probe (`phi_0`, `N_min`).\n")
    L.append("**Resolution.** The mismatch is resolved by ADDING an explicit function rather than by "
             "relabelling the existing one:\n")
    L.append("* `find_phi_fixed_budget_binary_search_deep` (new) — deepest accepted probe. This is "
             "the algorithm the consolidated pipeline reports, matching the thesis pseudocode and "
             "the `binary_deep` arm of `results/fine_sweep.csv`.\n"
             "* `find_phi_fixed_budget_binary_search_risk` (unchanged) — opening probe. Kept, "
             "untouched, so every earlier study that cites it still reproduces.\n")
    L.append("Both call the same `_binary_search_explore`, so at one configuration they differ in "
             "exactly one input to `risk_optimal_depth`.\n")
    L.append("The reported algorithm therefore CHANGES relative to `find_phi_fixed_budget_"
             "binary_search_risk`; this is not merely added telemetry. The size of the change, on "
             "common seeds and identical configurations:\n")
    if run_comparison:
        rows = pilot_comparison(R)
        L.append("| scenario | B | m' | conf | deepest-probe % | opening-probe % | Δ (pp) | "
                 "95% CI (deep) |")
        L.append("|---|---:|---:|---:|---:|---:|---:|---|")
        for r in rows:
            L.append(f"| {r['scenario']} | {r['budget']:,} | {r['m']} | {r['conf']} | "
                     f"{r['deep']:.2f} | {r['opening']:.2f} | {r['delta_pp']:+.2f} | {r['deep_ci']} |")
        L.append(f"\nR = {R:,} paired trials per cell, held-out seed "
                 f"{M.SEED_TEST}, common phase draws.\n")
    else:
        L.append("_(comparison skipped: run `python analysis/consolidated/audit.py` to measure it)_\n")

    L.append("## Run constants\n")
    L.append("The scattered `R_TEST` values in the pre-existing scripts (`qmetrology/config.py` "
             "50,000; `analysis/extensive_sweep.py` 40,000; `analysis/broad_dist_study.py` 30,000; "
             "`analysis/fine_sweep.py` 20,000) are NOT read by this pipeline. Every trial count, "
             "seed and grid comes from `qmetrology/manifest.py`, and every output row carries the "
             "`R`, `seed_test`, `seed_tune_blocks`, `algorithm`, `implementation_variant` and "
             "parameter dictionary it was produced with. The uncertainty layer reads `R` from the "
             "row.\n")
    L.append("## Definitions as implemented\n")
    L.append("```text\n"
             "N_opt          = max(1, floor(pi / (2 phi)))            qmetrology/trace.py:n_opt\n"
             "N_guess        per algorithm, see the table above; recorded BEFORE any safeguard\n"
             "N_star         the depth the exploitation measurement actually ran at; null if it\n"
             "               never ran\n"
             "B_exploration  sum of N_i * m_i over every probe before the exploitation measurement,\n"
             "               including repeated reverse-engineering pilot attempts after a zero\n"
             "               estimate\n"
             "exploration_share = B_exploration / nominal_budget\n"
             "```\n")
    L.append("## Known limitation\n")
    L.append("`../thesis/*.tex` is not present in this checkout, so the audit is written against "
             "the pseudocode as described in the handoff and in `results/BS_METHOD_DECISION.md`, "
             "not against the .tex sources directly. The pilot/cap behaviour of each function is "
             "verified against the code, and the `binary_deep` implementation is asserted "
             "trial-for-trial identical to the reference arm of `analysis/fine_sweep.py` "
             "(`tests/test_consolidated.py::test_binary_deep_matches_fine_sweep`).\n")
    return "\n".join(L)


if __name__ == "__main__":
    from pipeline_io import ensure_dirs, path
    ensure_dirs()
    quick = "--quick" in sys.argv
    txt = build(run_comparison=True, R=2000 if quick else 20_000)
    with open(path("algorithm_code_audit.md"), "w") as f:
        f.write(txt)
    print("wrote", path("algorithm_code_audit.md"))
